image: mcr.microsoft.com/dotnet/core/sdk:3.1

variables:
  AGENT_DOWNLOAD_URL: "http://s3.amazonaws.com/ddagent-windows-unstable/cf-windows-7.17.0-rc.4.git.35.7bd7ba0-1-x86_64.zip"
  TRACER_DOWNLOAD_URL: "https://docs.google.com/uc?export=download&id=1WngGuRLhmIyz8vQPRAKVB8d6J0OFD6RW"
  TRACER_CONTENT_DIR: $CI_PROJECT_DIR/content/Tracer
  AGENT_CONTENT_DIR: $CI_PROJECT_DIR/content/Agent

create-site-extension-package:
  tags: [ "runner:main", "size:2xlarge" ]
  script:
    - echo "Installing dependencies"
    - apt-get update
    - apt-get install unzip
    - echo "Downloading agent from ${AGENT_DOWNLOAD_URL}"
    - wget -O agent.zip $AGENT_DOWNLOAD_URL
    - unzip agent.zip -d agent-extract
    - echo "Downloading tracer from ${TRACER_DOWNLOAD_URL}"
    - wget -O tracer.zip $TRACER_DOWNLOAD_URL
    - unzip tracer.zip -d tracer-extract
    - echo "Moving agent executables and tracer binaries"
    - mkdir $TRACER_CONTENT_DIR
    - mv -v tracer-extract/* $TRACER_CONTENT_DIR
    - mv agent-extract/bin/agent/dogstatsd.exe $AGENT_CONTENT_DIR
    - mv agent-extract/bin/agent/trace-agent.exe agent-extract/bin/agent/datadog-trace-agent.exe
    - mv agent-extract/bin/agent/datadog-trace-agent.exe $AGENT_CONTENT_DIR
    - echo "Creating nuget package"
    - echo "Packing nuspec file via arcane roundabout csproj process"
    - dotnet pack Datadog.AzureAppServices.csproj -p:NoBuild=true -p:NoDefaultExcludes=true -o package
  artifacts:
    expire_in: 2 weeks
    paths:
      - package
